

import type { Metadata } from 'next'
import MainLayout from '@/components/layout/MainLayout';
import Link from 'next/link'
import '../styles/globals.css';
import MenuContextProvider from '@/context/MenuContext';
import "/node_modules/flag-icons/css/flag-icons.min.css";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MenuContextProvider>
        <MainLayout>
          {children}
        </MainLayout>
        </MenuContextProvider>




        {/* <div className="container mx-auto px-4 py-4">
      <ul>
          <li><Link href="/">Home</Link></li>
          <li><Link href="/dashboard">Dashboard</Link></li>
          <li><Link href="/settings">Settings</Link></li>
          <li><Link href="/cari">Cari orang</Link></li>
          <li><Link href="/post">post</Link></li>
          <li><Link href="/example">example</Link></li>
        </ul>

      </div>
       
        {children} */}
      </body>


    </html>
  )
}
